### ISSUE TITLE
Cannot authorize my App from Wordpress

### ISSUE THREAD

**Issue by drsceifers** [voceconnect/eventbrite-services#12]
I'm using the Eventbrite Services plugin in Wordpress. When I create the Keyring and then try to authorize the connection, it gives me this error: There was a problem authorizing with Eventbrite. Please try again in a moment.

I am trying to connect to show Dr Patel's events on his website http://thelivingproofinstitute.com/

The error message gives me no idea where to go to fix the issue. Can you authorize it from your end?

**Comment by smccafferty** [comment]
@drsceifers Responded to you in the WordPress.org support thread. Going to close this and we can continue the conversation there.
