### ISSUE TITLE
Connect with Eventbrite ->The application you're trying to use has made an invalid request to Eventbrite. Please contact the application developer. 

### ISSUE THREAD

**Issue by crhall** [voceconnect/eventbrite-services#8]
When I click "Connect with Eventbrite" I get the following error....The application you're trying to use has made an invalid request to Eventbrite. Please contact the application developer. 

WP 4.1.1

**Comment by smccafferty** [comment]
This is likely because the API key has not been specified, you will need to create an API key via the Keyring plugin that is installed with the Eventbrite Sevices plugin, first. Once Keyring has the Eventbrite API information you can then connect to Eventbrite via the settings page.

**Comment by crhall** [comment]
Quick question - does this only work with the mentioned themes? I was expecting some short codes or something?

**Comment by smccafferty** [comment]
Yes, currently it will only display Eventbrite data when using the Eventbrite themes. Unfortunately, there are no shortcodes to display Eventbrite data.

However, you could create methods calling the Eventbrite API methods in the plugin. The big benefit of this plugin is to do the heavy lifting of handshaking your site to Eventbrite as well as lay the ground work for the Eventbrite themes.
